import type { Metadata } from "next";
import { Marcellus_SC } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/header";

const marcelusSC = Marcellus_SC({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="retro">
      <body
        className={`${marcelusSC} antialiased`}
      >
        <AppHeader/>
        {children}
      </body>
    </html>
  );
}
